# Names of dialog functions "00" through "73"

# "Rank Requirement" explanation:
# http://wiki.theassimilationlab.com/mmw/Creation_and_Management_of_Factions#Enlisting_and_career_growth._Working_with_dialogue.

dialog_function_type_names = {
    b"00": "Rank Low",
    b"01": "Rank High",
    b"02": "Rank Requirement",
    b"03": "NPC Reputation",
    b"04": "NPC Health Percent",
    b"05": "Player Reputation",
    b"06": "Player Level",
    b"07": "Player HealthPercent",
    b"08": "Player Magicka",
    b"09": "Player Fatigue",
    b"10": "Player Strength",
    b"11": "Player Block Skill",
    b"12": "Player Armorer Skill",
    b"13": "Player Medium Armor Skill",
    b"14": "Player Heavy Armor Skill",
    b"15": "Player Blunt Weapon Skill",
    b"16": "Player Long Blade Skill",
    b"17": "Player Axe Skill",
    b"18": "Player Spear Skill",
    b"19": "Player Athletics Skill",
    b"20": "Player Enchant Skill",
    b"21": "Player Destruction Skill",
    b"22": "Player Alteration Skill",
    b"23": "Player Illusion Skill",
    b"24": "Player Conjuration Skill",
    b"25": "Player Mysticism Skill",
    b"26": "Player Restoration Skill",
    b"27": "Player Alchemy Skill",
    b"28": "Player Unarmored Skill",
    b"29": "Player Security Skill",
    b"30": "Player Sneak Skill",
    b"31": "Player Acrobatics Skill",
    b"32": "Player LightArmor Skill",
    b"33": "Player ShortBlade Skill",
    b"34": "Player Marksman Skill",
    b"35": "Player Merchantile Skill",
    b"36": "Player Speechcraft Skill",
    b"37": "Player Hand To Hand Skill",
    b"38": "Player Gender (Male: 0, Female: 1)",
    b"39": "Player Expelled From NPC Faction",
    b"40": "Player Common Disease",
    b"41": "Player Blight Disease",
    b"42": "Player Clothing Modifier",
    b"43": "Player Crime Level",
    b"44": "NPC Same Gender As Player",
    b"45": "NPC Same Race As Player",
    b"46": "NPC Same Faction As Player",
    b"47": "Player Rank Minus NPC Rank",
    b"48": "Player Is Detected",
    b"49": "NPC Is Alarmed",
    b"50": "Previous Dialog Choice",
    b"51": "Player Intelligence",
    b"52": "Player Willpower",
    b"53": "Player Agility",
    b"54": "Player Speed",
    b"55": "Player Endurance",
    b"56": "Player Personality",
    b"57": "Player Luck",
    b"58": "Player Corpus",
    b"59": "Weather",
    b"60": "Player Is Vampire",
    b"61": "NPC Level",
    b"62": "NPC Attacked",
    b"63": "NPC Talked To Player",
    b"64": "Player Health Percent",
    b"65": "NPC Is Targeting Creature",
    b"66": "Friendly Hits",
    b"67": "NPC Fight",
    b"68": "NPC Hello",
    b"69": "NPC Alarm",
    b"70": "NPC Flee",
    b"71": "NPC Should Attack Player",
    b"72": "NPC Is Werewolf",
    b"73": "Player Werewolf Kills",
}
